name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.7

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Build backend exe
        run: |
          cd backend
          pyinstaller --onefile app.spec

      - name: Install Electron dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run build:electron

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/**/*
          tag: ${{ github.ref }}
